### ISSUE TITLE
Array not sorted in binary_search.cpp

### ISSUE THREAD

**Issue by aedorado** [salman-bhai/DA_A_DS#11]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Check out this [link](https://github.com/salman-bhai/E-Manager/blob/master/README.md) to understand better.

The array is not sorted in [binary-search.cpp](https://github.com/salman-bhai/DA_A_DS/blob/master/Algorithms/Search/binary-search/binary-search.cpp)

**Comment by TuhinKundu** [comment]
Do you want binary-search.cpp to be corrected?

**Comment by AnanyaSharma22** [comment]
`#include<iostream>
using namespace.std;
void main()
{
	clrscr();
	int n, i, arr[50], search, first, last, middle;
	cout<<"Enter the elements in sorted order:";
	cin>>n;
	cout<<"Enter "<<n<<" number :";
	for (i=0; i<n; i++)
	{
		cin>>arr[i];
	}
	cout<<"Enter a number to find :";
	cin>>search;
	first = 0;
	last = n-1;
	middle = (first+last)/2;
	while (first <= last)
	{
		if(arr[middle] < search)
		{
			first = middle + 1;

		}
		else if(arr[middle] == search)
		{
			cout<<search<<" found at location "<<middle+1<<"\n";
			break;
		}
		else
		{
			 last = middle - 1;
		}
		middle = (first + last)/2;
	}
	if(first > last)
	{
		cout<<"Not found! "<<search<<" is not present in the list.";
	}
}`

**Comment by salman-bhai** [comment]
Hey @AnanyaSharma22 kindly send a PR instead of commenting on the code here.
@TuhinKundu yes, kindly send a PR referencing this issue.
@aedorado Thanks for pointing it out! :+1:

**Comment by TuhinKundu** [comment]
Working on it

**Comment by TuhinKundu** [comment]
See PR has been merged regarding this. Is this issue still open?

**Comment by salman-bhai** [comment]
The Pull Request has been sent, @TuhinKundu
