### ISSUE TITLE
Python Implementation of Data Structures

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#14]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Kindly claim for the following Data Structures:
1. Stacks
2. Queues
3. Trees
4. Linked Lists
5. Graphs
6. Hash

**Comment by PassaEP** [comment]
CLAIM! :) I would love to work on this!

**Comment by richa-coder** [comment]
Claim

**Comment by salman-bhai** [comment]
Kindly specify which Data Structures you'll be working on! @PassaEP and @richa-coder . Kindly do not claim Data Structures which are already claimed by other people.

**Comment by alexkiura** [comment]
I'd like to Claim implementing stacks @salman-bhai

**Comment by richa-coder** [comment]
i will implement the others then.U will get all the codes by tomorrow.



[image: --]

Richa Singh
[image: https://]about.me/richa-singh
<https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by adriaferre** [comment]
W would like ot claim implmenting queue @salman-bhai . Thank you

**Comment by salman-bhai** [comment]
Go ahead, @adriaferre 
@richa-coder Kindly claim an the Issue again if you wish to push code!

**Comment by jainayush975** [comment]
I'd like to Claim implementing prims algorithm @salman-bhai

**Comment by salman-bhai** [comment]
@jainayush975 Just check it hasn't been done or not before sending your PR.

**Comment by jainayush975** [comment]
I claim to implement LIS and LCS @salman-bhai

**Comment by salman-bhai** [comment]
Hey, I've made separate Issues for this. Kindly check the `Issues` tab for more details!
