### ISSUE TITLE
Java Implementation of Data Structures

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#15]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Kindly claim for the following Data Structures:
1. Stacks
2. Queues
3. Trees
4. Linked Lists
5. Graphs
6. Hash

**Comment by AntPeixe** [comment]
Hi, I would implement the stacks, queues and linked lists but I think you already added them to the code.

Tell me if you are still interested in those.
