### ISSUE TITLE
Python implementation of Graph Algorithms

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#18]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

The following Algorithms need to be added:
1. BFS
2. DFS
3. Kruskal's
4. Prim's
5. Dijkstra's
6. Floyd-Warshall Algorithm

**Comment by adriaferre** [comment]
I would like to do the DFS. Thank you.

**Comment by salman-bhai** [comment]
Issue has been created separately in the `Issues` tab. Kindly take a look!
