### ISSUE TITLE
Java Implementation of Search Algorithms

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#21]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Kindly claim for the following Search Algorithms:
1. Linear Search
2. Binary Search

**Comment by rahul26081995** [comment]
I will like to take binary search.

**Comment by salman-bhai** [comment]
Go ahead! @rahul26081995

**Comment by hiteshgarg14** [comment]
I will like to take linear search.

**Comment by salman-bhai** [comment]
Well done guys.
