### ISSUE TITLE
Python Implementation of Search Algorithms

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#22]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Kindly claim for the following Search Algorithms:
1. Linear Search
2. Binary Search

**Comment by goyaljai** [comment]
i would like to take python's

**Comment by salman-bhai** [comment]
Which Algorithm, @goyaljai

**Comment by goyaljai** [comment]
both

**Comment by goyaljai** [comment]
or binary search

**Comment by salman-bhai** [comment]
First submit Binary Search. If no one claims it by then, take up Linear Search as well.

**Comment by zorroblue** [comment]
I want to do linear search. Can I take it up?
@salman-bhai

**Comment by adriaferre** [comment]
I would like to participate too.

**Comment by adriaferre** [comment]
I've just pull-requested the binarySearch. I do it recursive.

**Comment by alexkiura** [comment]
Can i take up the Linear search @salman-bhai ?

**Comment by salman-bhai** [comment]
@alexkiura Everything is already done!
