### ISSUE TITLE
Python Implementation of Sorting Algorithms

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#4]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Kindly claim for the following Sorting Algorithms:
1. Selection Sort
2. Bubble Sort
3. Merge Sort
4. Quick Sort
5. Shell Sort
6. Topological Sort

**Comment by rahul-kumi** [comment]
I will take up this!

**Comment by rahul-kumi** [comment]
dude self assigning...

**Comment by mridulg** [comment]
Hi, could you give specific details regarding what you require?

**Comment by TuhinKundu** [comment]
Please specify programs do you want to be implemented into python?

**Comment by richa-coder** [comment]
I want to start on this.

**Comment by salman-bhai** [comment]
Go ahead. Make sure you write the Algorithms in python 2.7

**Comment by TuhinKundu** [comment]
Working on Quick sort in python.

**Comment by adriaferre** [comment]
I would like to do the merge sort. Thank you.

**Comment by salman-bhai** [comment]
Cool go ahead @TuhinKundu @adriaferre

**Comment by salman-bhai** [comment]
Issue has been created separately in the `Issues` tab. Kindly take a look!
