### ISSUE TITLE
Add Dijkstra's Algorithm in the following Languages

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#44]
The following Algorithm needs to be implemented in the following languages.
- [x] C
- [x] C++
- [x] Python
- [x] Java

Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.
4. Make sure you put in the **proper folder**. If you do not know where to push the code for the Algorithm, feel free to ask in the comments section below. :smile:

**Comment by shrawnz** [comment]
Claiming C++

**Comment by amanmehta-maniac** [comment]
Claiming C.

**Comment by salman-bhai** [comment]
Go ahead people! Just don't forget to reference the Issue!

**Comment by laps15** [comment]
Claiming C++

**Comment by TuhinKundu** [comment]
Claiming python!

**Comment by noveens** [comment]
Claiming Java.

**Comment by Akshaj5** [comment]
Claiming C
As amanmehta-maniac did not send any pull request.
