### ISSUE TITLE
Add Heap-Sort for the following languages

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#50]
The following Algorithm needs to be implemented in the following languages.
- [x] C
- [x] C++
- [x] Python
- [x] Java

Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.
4. Make sure you put in the **proper folder**. If you do not know where to push the code for the Algorithm, feel free to ask in the comments section below. :smile:

**Comment by nikitakorba** [comment]
Claiming C++

**Comment by salman-bhai** [comment]
Go ahead, @nikitakorba !

**Comment by shubham-k7** [comment]
can i claim for C?

**Comment by salman-bhai** [comment]
Go ahead, @shubham-k7

**Comment by Viditjn** [comment]
Claim to work in java

**Comment by amanshahi** [comment]
Doing in py.

**Comment by NakulVaidya** [comment]
as viditjn is unable to do a pull request . I would like to do it in java.
