### ISSUE TITLE
Add Quick Sort for the following Languages

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#53]
The following Algorithm needs to be implemented in the following languages.
- [x] C
- [x] C++
- [x] Python
- [x] Java

Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.
4. Make sure you put in the **proper folder**. If you do not know where to push the code for the Algorithm, feel free to ask in the comments section below. :smile:

**Comment by BrunoTissei** [comment]
I'll work on the C version.

**Comment by menikhilpandey** [comment]
Hi @salman-bhai I wish to claim python version of quick sort for implementation.

**Comment by nikitakorba** [comment]
I'd like to take C++ Quick Sort

**Comment by salman-bhai** [comment]
Go ahead! @menikhilpandey @nikitakorba

**Comment by mlterpstra92** [comment]
I'd like to implement the Java version

**Comment by salman-bhai** [comment]
Hey Kindly check the new Issues Tab which I've created!

**Comment by salman-bhai** [comment]
Hey, @mlterpstra92 Go ahead! I'm sorry for the confusion!
