### ISSUE TITLE
Add Shell-Sort for the following languages

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#56]
The following Algorithm needs to be implemented in the following languages.
- [x] C
- [x] C++
- [x] Python
- [x] Java

Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.
4. Make sure you put in the **proper folder**. If you do not know where to push the code for the Algorithm, feel free to ask in the comments section below. :smile:

**Comment by Arunraj97** [comment]
I would like to claim for this in C

**Comment by amanshahi** [comment]
I'am doing in python.
