### ISSUE TITLE
Add Disjoint Sets for the following languages

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#61]
The following Data Structure needs to be implemented in the following languages.
- [x] C
- [x] C++
- [x] Python
- [x] Java

Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.
4. Make sure you put in the **proper folder**. If you do not know where to push the code for the Data Structures, feel free to ask in the comments section below. :smile:

**Comment by NikhilGogate13** [comment]
I would do tree implementation of disjoint sets(Having Different forest as set) in C.

**Comment by NikhilGogate13** [comment]
After acceptance of this pull request shouldn't I should be in contributers.My name is not on contributers page.

**Comment by patniharshit** [comment]
I would like to contribute C++ implementation of Disjoint-Sets.

**Comment by NakulVaidya** [comment]
I would like to contribute java implementation of disjoint-sets.

**Comment by Akshaj5** [comment]
I would like to contribute python implementation of Disjoint-sets.
