### ISSUE TITLE
Add Doubly Linked List in the following languages

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#63]
The following Data Structure needs to be implemented in the following languages.
- [x] C
- [x] C++
- [x] Python
- [x] Java

Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.
4. Make sure you put in the **proper folder**. If you do not know where to push the code for the Data Structures, feel free to ask in the comments section below. :smile:

**Comment by alinarezrangel** [comment]
Hi @salman-bhai, I will work on the C++ version, but I have a question: Is required to use the C++ STL?

**Comment by salman-bhai** [comment]
Preferably, don't use STL, @alinarezrangel !

**Comment by shubham-k7** [comment]
can i claim the code for C?

**Comment by salman-bhai** [comment]
It's done already. Check the description.

**Comment by shrawnz** [comment]
Claiming c++

**Comment by a-lakh** [comment]
doing it injava

**Comment by Viditjn** [comment]
I claim for java

**Comment by shiva1208** [comment]
I want to claim for c.

**Comment by Bargsteen** [comment]
I would like to claim in Java

**Comment by yash-iiith** [comment]
I would like to claim in Python.

**Comment by pranavgoel25** [comment]
I would like to claim for Java
