### ISSUE TITLE
Add README for Data Structures

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#73]
Hey! Looks like you're on your way to your **First Pull Request**. You don't even need to write a single line of code for this!

Welcome to the **Hacktoberfest**! :smile: This is a First-Timer Issue to increase your confidence in the field of Open-Source. All you have to do is send a Pull Request (Click [here](https://github.com/salman-bhai/DA_A_DS/blob/master/CONTRIBUTING.md) to see how to send a Pull Request).
 
All you have to do is explain the Data Structure and an appropriate explanation for the same. Just make sure you explain the concepts in the respective Data Structure 

- [ ] Disjoint Sets
- [ ] Hashing
- [ ] Singly Linked List
- [ ] Doubly Linked List
- [ ] Circular Linked List
- [ ] Queues
- [ ] Stacks
- [ ] Binary Search Trees
- [x] AVL Trees
- [ ] Binary Trees
- [ ] Tries

Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.
4. Make sure you put in the **proper folder**. If you do not know where to push the code for the Data Structures, feel free to ask in the comments section below. :smile:  
5. Kindly claim one Data Structure before moving to another!

**Comment by mlterpstra92** [comment]
Hi, can I claim this one?

**Comment by salman-bhai** [comment]
Which Data Structure, @mlterpstra92

**Comment by mlterpstra92** [comment]
I can explain the AVL tree :-)
