### ISSUE TITLE
Add README for Search Algorithms

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#75]
Hey! Looks like you're on your way to your **First Pull Request**. You don't even need to write a single line of code for this!

Welcome to the **Hacktoberfest**! :smile: This is a First-Timer Issue to increase your confidence in the field of Open-Source. All you have to do is send a Pull Request (Click [here](https://github.com/salman-bhai/DA_A_DS/blob/master/CONTRIBUTING.md) to see how to send a Pull Request).
 
All you have to do is explain the Data Structure and an appropriate explanation for the same. Just make sure you explain the concepts in the respective Data Structure 

- [x] Linear Search
- [x] Binary Search

Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.
4. Make sure you put in the **proper folder**. If you do not know where to push the code for the Data Structures, feel free to ask in the comments section below. :smile:  
5. Kindly claim one Search Algorithm before moving to another!

**Comment by Prernajain2** [comment]
Hi i would like to claim this one

**Comment by salman-bhai** [comment]
Which Search Algorithm, @Prernajain2 ?

**Comment by Prernajain2** [comment]
Linear

**Comment by salman-bhai** [comment]
Go ahead, @Prernajain2

**Comment by amanmehta-maniac** [comment]
I would like to work for this issue. Can I get this? Thanks

**Comment by salman-bhai** [comment]
You can work on Binary Search, @amanmehta-maniac . If @Prernajain2 doesnt send a PR in 12 hours you can send a PR for Linear Search as well.

**Comment by aryanhimanshu** [comment]
Hey!
I would like to claim linear search.

**Comment by amanmehta-maniac** [comment]
I have created a new PR for binary search.

**Comment by Bargsteen** [comment]
I would like to claim Linear Search

**Comment by pprintz** [comment]
I would like to claim linear or binary search

**Comment by Radhikadua123** [comment]
Hey!
I  would like to claim linear or binary search.Can i get any of these? Thanks

**Comment by salman-bhai** [comment]
Linear Search is remaining!

**Comment by pranavgoel25** [comment]
I would like to claim linear search.

**Comment by Radhikadua123** [comment]
I would like to claim linear search.Can i work on it?

**Comment by pranavgoel25** [comment]
https://github.com/salman-bhai/DA_A_DS/pull/177
