### ISSUE TITLE
Java Implementation of Sorting Algorithms

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/DA_A_DS#9]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Kindly claim for the following Sorting Algorithms:
1. Selection Sort
2. Bubble Sort
3. Merge Sort
4. Quick Sort
5. Shell Sort
6. Topological Sort

**Comment by Nitish18** [comment]
@salman-bhai , I am working on this issue.

**Comment by zorroblue** [comment]
I want to do merge sort @salman-bhai

**Comment by anumpatel** [comment]
@salman-bhai  I will work on Quick Sort if anybody hasn't started it.

**Comment by salman-bhai** [comment]
@anumpatel Kindly check he contents of the repository before pushing your code! Thanks again!

**Comment by salman-bhai** [comment]
Issue has been created separately in the `Issues` tab. Kindly take a look!
